# -*- coding: utf-8 -*-
EMAIL = "dhalska2@gmail.com"
KO = {
 "label": "한국어", "html": "ko", "nav": ["소개", "개인정보처리방침", "이용약관", "지원", "계정 삭제"],
 "tag": "문서를 스캔하고, 서명하고, 안전하게 보관하세요",
 "intro": "종이 문서를 몇 초 만에 PDF로 스캔하고, 글자 검색·서명·양식 작성·암호 설정·합치기까지 한 앱에서 끝내세요.",
 "features": ["가장자리 자동 인식 스캔과 PDF 저장", "PDF 합치기·나누기·서명·양식 작성·암호 설정", "스캔과 글자 인식은 기기 안에서 처리, 클라우드 백업은 선택"],
 "offline": "광고와 추적이 없고, 문서는 기본적으로 내 기기에만 저장됩니다. 로그인하고 PRO 클라우드 백업을 켠 경우에만 서버에 저장됩니다.",
 "date": "시행일: 2026년 10월 10일",
 "privacy_title": "PageBeam 개인정보처리방침",
 "privacy_intro": "PageBeam은 Next Studio가 제공하는 문서·PDF 스캐너 앱입니다. 로그인하지 않으면 모든 문서가 내 기기에만 저장되고 서버로 전송되지 않습니다.",
 "privacy": [
  ("기기에 저장하는 정보", "스캔한 사진, 만든 PDF 문서와 미리보기, 글자 인식으로 읽은 검색용 글자, 저장한 서명 이미지, 화면·언어·스캔 설정은 기기 안에만 저장됩니다. 스캔과 글자 인식은 기기에서 처리되며 사진이나 글자가 외부로 전송되지 않습니다."),
  ("카메라와 사진", "카메라는 문서를 스캔할 때만 사용합니다. 사진 가져오기는 운영체제의 사진 선택기를 쓰므로 사진 보관함 전체에 접근하지 않으며, 사용자가 고른 사진만 앱으로 전달됩니다. 권한은 기기 설정에서 끌 수 있습니다."),
  ("로그인과 서버에 저장하는 정보", "클라우드 백업·동기화를 쓰려고 Apple(Android는 Google) 계정으로 로그인하면 계정 식별자와 이메일(제공자가 전달하는 경우)이 인증 서비스(Supabase)에 저장됩니다. 로그인은 선택이며, 스캔·PDF 도구·구독 구매에는 필요하지 않습니다."),
  ("클라우드 백업", "PRO 구독자가 로그인하고 동기화를 켜면 PDF 문서, 미리보기 이미지, 서명 이미지, 문서 제목·폴더·쪽 수, 검색용 글자가 서버(Supabase)에 저장되어 다른 기기와 동기화됩니다. 암호를 건 PDF는 암호화된 파일 그대로 올라가며 미리보기와 검색용 글자는 올라가지 않습니다. 동기화를 끄거나 로그인하지 않으면 문서는 서버로 가지 않습니다."),
  ("구독과 결제", "결제는 Apple App Store 또는 Google Play가 처리하며 PageBeam은 카드 정보를 받지 않습니다. 로그인하지 않은 상태의 구독 상태는 기기와 스토어에서만 확인합니다. 로그인한 경우 클라우드 백업 권한을 위해 스토어 구매 영수증(거래 번호, 상품, 만료일)을 서버로 보내 Apple 또는 Google에 검증하고 구독 상태를 저장합니다."),
  ("오류 정보", "앱이 비정상 종료되면 원인 파악을 위해 Firebase Crashlytics로 오류 기록(기기 모델, 운영체제 버전, 앱 버전, 오류 내용, 임의의 설치 식별자)이 전송됩니다. 문서 내용·제목·사진은 포함하지 않습니다. 개발 중 빌드에서는 수집하지 않습니다."),
  ("광고와 추적", "PageBeam에는 광고가 없고, 광고 식별자(IDFA)를 읽지 않으며, 앱 간 추적을 하지 않습니다. 제3자 분석 도구도 쓰지 않습니다."),
  ("보관과 삭제", "기기의 문서는 앱을 삭제하거나 문서를 삭제하면 지워집니다. 서버의 데이터는 로그인 상태에서 설정 → 계정·백업 → 계정 삭제를 누르면 문서·서명·구독 기록이 삭제되고, Apple로 로그인했다면 Apple과의 연결도 해제됩니다. 앱에 접근할 수 없으면 계정 삭제 페이지의 안내에 따라 이메일로 요청할 수 있습니다."),
  ("처리 위탁", "서버 저장과 인증은 Supabase, 오류 수집은 Google(Firebase), 결제는 Apple·Google이 처리합니다. 이 외의 제3자에게 정보를 판매하거나 제공하지 않습니다."),
  ("아동 및 변경", "PageBeam은 일반 사용자를 위한 앱이며 아동의 개인정보를 고의로 수집하지 않습니다. 방침이 바뀌면 이 페이지의 시행일을 갱신합니다."),
 ],
 "terms_title": "PageBeam 이용약관",
 "terms_intro": "이 약관은 Next Studio가 제공하는 PageBeam 앱의 이용 조건을 정합니다. 앱을 설치하거나 사용하면 이 약관에 동의한 것으로 봅니다.",
 "terms": [
  ("서비스", "PageBeam은 문서를 스캔해 PDF로 저장하고, 합치기·나누기·이미지 내보내기를 할 수 있는 앱입니다. 글자 인식(OCR)·서명·양식 작성·암호 설정·클라우드 백업과 동기화는 PRO 구독 기능입니다."),
  ("구독과 결제", "PRO는 주간 또는 연간 자동 갱신 구독이며 신규 구독자에게는 무료 체험이 제공될 수 있습니다. 가격은 구독 전에 앱에 표시되며 결제는 Apple ID 또는 Google 계정에 청구됩니다. 구독은 현재 기간이 끝나기 최소 24시간 전에 해지하지 않으면 자동으로 갱신됩니다. 해지와 환불은 각 스토어의 구독 관리와 환불 정책에 따릅니다. 구독이 끝나도 기기의 문서는 그대로 남고 PRO 기능과 새 변경의 클라우드 업로드만 제한됩니다."),
  ("사용자의 문서", "스캔한 문서와 사진의 권리는 사용자에게 있습니다. 타인의 권리를 침해하거나 불법적인 문서를 스캔·저장·공유하지 마세요."),
  ("서명 기능", "앱에서 넣는 서명은 손으로 그린 이미지를 PDF에 얹는 기능이며 인증기관이 발급하는 공인 전자서명이 아닙니다. 서명의 법적 효력은 문서의 종류와 국가·상대방의 요구에 따라 다르므로 사용자가 확인해야 합니다."),
  ("암호와 백업", "PDF 암호는 사용자만 알며 분실하면 복구할 수 없습니다. 기기 분실·고장에 대비해 중요한 문서는 클라우드 백업이나 별도 보관으로 백업하세요."),
  ("금지 행위", "서비스를 해킹하거나 비정상적인 방법으로 접근하는 행위, 다른 사람의 계정을 도용하는 행위, 서버에 과도한 부하를 주는 행위를 금지합니다."),
  ("서비스 변경과 책임의 제한", "기능은 개선을 위해 바뀌거나 중단될 수 있습니다. Next Studio는 법이 허용하는 범위에서 글자 인식 오류, 데이터 손실, 앱 이용으로 생긴 간접 손해에 대해 책임지지 않습니다."),
  ("준거법과 문의", "이 약관은 대한민국 법을 따릅니다. 문의는 아래 이메일로 보내 주세요. 약관이 바뀌면 이 페이지의 시행일을 갱신합니다. 구독에는 Apple의 표준 사용권 계약(EULA)도 적용됩니다."),
 ],
 "support_title": "PageBeam 도움말 및 지원",
 "support_intro": "앱을 쓰다가 문제가 생기면 아래를 확인하고, 해결되지 않으면 이메일로 문의해 주세요.",
 "support": [
  ("스캐너가 열리지 않을 때", "기기 설정에서 PageBeam의 카메라 권한이 켜져 있는지 확인하세요. 권한을 켠 뒤 앱을 다시 실행해 보세요."),
  ("글자가 잘못 읽히거나 검색이 안 될 때", "설정 → 스캔 → 글자 인식 언어에서 문서의 언어(로마자, 한국어, 일본어, 중국어)를 켜세요. 글자 인식은 PRO 기능이며 인쇄된 글자에 가장 잘 맞습니다. 밝고 평평하게 촬영하면 정확도가 올라갑니다."),
  ("PDF 암호를 잊었을 때", "PDF 암호는 복구할 수 없습니다. 암호를 풀 방법이 없으니 암호는 따로 안전하게 보관하세요."),
  ("구독 복원과 해지", "구독 화면이나 설정에서 \"구매 복원\"을 누르세요. 해지는 iPhone의 설정 → Apple ID → 구독, Android의 Google Play → 구독에서 할 수 있습니다. 로그인 없이도 구매와 복원이 됩니다."),
  ("클라우드 동기화가 안 될 때", "설정 → 계정·백업에서 로그인하고, PRO가 활성인지, 문서 동기화가 켜져 있는지, 인터넷에 연결돼 있는지 확인하세요. 50MB를 넘는 문서는 동기화되지 않습니다."),
  ("문의할 때", "기기 종류, 운영체제 버전, 앱 버전, 문제를 다시 만드는 순서를 적어 보내 주세요. 문서 내용은 보내지 않아도 됩니다."),
 ],
 "delete_title": "PageBeam 계정 및 데이터 삭제",
 "delete_intro": "PageBeam은 로그인 없이도 쓸 수 있고, 로그인해 클라우드 백업을 켠 경우에만 서버에 데이터가 저장됩니다. 아래 방법으로 삭제할 수 있습니다.",
 "delete-account": [
  ("앱에서 삭제하기 (권장)", "PageBeam에서 설정 → 계정·백업 → 계정 삭제를 누르세요. 서버에 저장된 모든 문서·서명·구독 기록이 삭제되고, Apple로 로그인했다면 연결도 해제됩니다. 구독은 자동으로 해지되지 않으므로 스토어에서 따로 해지하세요."),
  ("앱에 접근할 수 없을 때", f"가입한 로그인(Apple 또는 Google)과 앱 이름을 적어 {EMAIL}로 삭제를 요청해 주세요. 본인 확인 후 영업일 기준 7일 안에 삭제하고 알려 드립니다."),
  ("기기의 데이터", "기기에만 저장된 문서는 앱을 삭제하면 함께 지워집니다. 앱의 계정 삭제는 기기의 문서를 지우지 않습니다."),
  ("삭제되는 정보", "클라우드에 올라간 PDF 문서와 미리보기, 서명 이미지, 문서 제목·폴더 정보, 구독 상태 기록이 삭제됩니다. 스토어의 결제 내역은 Apple·Google이 관리하므로 삭제되지 않습니다."),
 ],
 "contact": "문의", "skip": "본문으로 이동", "choose": "언어 선택", "copyright": "© 2026 Next Studio · 넥스트 스튜디오",
}
EN = {
 "label": "English", "html": "en", "nav": ["Overview", "Privacy", "Terms", "Support", "Delete account"],
 "tag": "Scan, sign and keep your documents safe",
 "intro": "Scan paper into PDF in seconds, then search the text, sign, fill forms, password-protect and merge, all in one app.",
 "features": ["Auto edge detection scanning and PDF saving", "Merge, split, sign, fill forms and password-protect PDFs", "Scanning and text recognition happen on your device; cloud backup is optional"],
 "offline": "No ads and no tracking. Your documents stay on your device unless you sign in and turn on PRO cloud backup.",
 "date": "Effective October 10, 2026",
 "privacy_title": "PageBeam Privacy Policy",
 "privacy_intro": "PageBeam is a document and PDF scanner app provided by Next Studio. If you do not sign in, all your documents stay on your device and nothing is sent to a server.",
 "privacy": [
  ("Information stored on your device", "Scanned photos, the PDF documents and previews you create, the searchable text read by text recognition, saved signature images, and display, language and scan settings are stored only on your device. Scanning and text recognition run on your device; photos and text are not sent anywhere."),
  ("Camera and photos", "The camera is used only to scan documents. Importing photos uses the operating system photo picker, so the app does not access your whole photo library; only the photos you choose are passed to the app. You can turn off the permission in device settings."),
  ("Sign-in and information stored on our server", "If you sign in with Apple (Google on Android) to use cloud backup and sync, your account identifier and email (if the provider shares it) are stored with our authentication service (Supabase). Signing in is optional and is not needed to scan, use the PDF tools, or buy a subscription."),
  ("Cloud backup", "If you are a signed-in PRO subscriber and turn on sync, your PDF documents, preview images, signature images, document titles, folders, page counts and searchable text are stored on our server (Supabase) and synced to your other devices. Password-protected PDFs are uploaded as encrypted files, without previews or searchable text. If you turn sync off or do not sign in, your documents are not sent to a server."),
  ("Subscriptions and payments", "Payments are handled by the Apple App Store or Google Play. PageBeam never receives your card details. When you are not signed in, your subscription status is checked only on your device and with the store. When you are signed in, the app sends the store purchase receipt (transaction ID, product, expiry date) to our server, which verifies it with Apple or Google and stores the subscription status for cloud backup access."),
  ("Crash information", "If the app crashes, an error report (device model, operating system version, app version, error details and a random installation ID) is sent to Firebase Crashlytics to help us fix the problem. It does not include document content, titles or photos. Development builds do not collect it."),
  ("Ads and tracking", "PageBeam has no ads, does not read the advertising identifier (IDFA), and does not track you across apps. We do not use third-party analytics tools."),
  ("Retention and deletion", "Documents on your device are removed when you delete the app or a document. Server data (documents, signatures, subscription records) is deleted when you choose Settings → Account & backup → Delete account while signed in; if you used Sign in with Apple, the link to Apple is revoked too. If you cannot open the app, you can request deletion by email as described on the delete-account page."),
  ("Service providers", "Supabase provides authentication and server storage, Google (Firebase) provides crash reporting, and Apple and Google process payments. We do not sell your information or share it with anyone else."),
  ("Children and changes", "PageBeam is for general users and does not knowingly collect children's personal information. If this policy changes, we update the effective date on this page."),
 ],
 "terms_title": "PageBeam Terms of Use",
 "terms_intro": "These terms set the conditions for using the PageBeam app provided by Next Studio. By installing or using the app you agree to these terms.",
 "terms": [
  ("Service", "PageBeam scans documents into PDF and lets you merge, split and export pages as images. Text recognition (OCR), signing, form filling, password protection, and cloud backup and sync are PRO subscription features."),
  ("Subscriptions and payment", "PRO is a weekly or yearly auto-renewing subscription, and new subscribers may be offered a free trial. The price is shown in the app before you subscribe, and payment is charged to your Apple ID or Google account. A subscription renews automatically unless cancelled at least 24 hours before the end of the current period. Cancellation and refunds follow each store's subscription management and refund policies. When a subscription ends, your documents stay on your device; only PRO features and cloud upload of new changes are limited."),
  ("Your documents", "You own your scanned documents and photos. Do not scan, store or share documents that infringe other people's rights or are unlawful."),
  ("Signing feature", "A signature you add is a hand-drawn image placed on the PDF. It is not a certified digital signature issued by a certification authority. Whether it is legally valid depends on the document, the country and the other party's requirements, which you are responsible for checking."),
  ("Passwords and backups", "Only you know a PDF password, and it cannot be recovered if you lose it. Keep important documents backed up with cloud backup or separately in case your device is lost or damaged."),
  ("Prohibited conduct", "You may not hack the service or access it by abnormal means, use someone else's account, or place excessive load on our servers."),
  ("Changes and limitation of liability", "Features may change or be discontinued as we improve the service. To the extent permitted by law, Next Studio is not liable for text recognition errors, data loss, or indirect damages arising from use of the app."),
  ("Governing law and contact", "These terms are governed by the laws of the Republic of Korea. Contact us at the email below. If the terms change, we update the effective date on this page. Apple's standard End User License Agreement (EULA) also applies to subscriptions."),
 ],
 "support_title": "PageBeam Help and Support",
 "support_intro": "If you run into a problem, check the items below. If it is not resolved, email us.",
 "support": [
  ("If the scanner does not open", "Check that camera permission for PageBeam is on in device settings, then relaunch the app."),
  ("If text is read wrongly or search does not work", "In Settings → Scanning → Text recognition languages, turn on the language of your document (Latin letters, Korean, Japanese or Chinese). Text recognition is a PRO feature and works best on printed text. Shooting flat and well lit improves accuracy."),
  ("If you forgot a PDF password", "A PDF password cannot be recovered. Keep your passwords somewhere safe."),
  ("Restore or cancel a subscription", "Tap \"Restore purchases\" on the subscription screen or in Settings. To cancel, use Settings → Apple ID → Subscriptions on iPhone, or Google Play → Subscriptions on Android. Purchasing and restoring work without signing in."),
  ("If cloud sync does not work", "In Settings → Account & backup, check that you are signed in, PRO is active, document sync is on, and you are online. Documents over 50 MB are not synced."),
  ("When contacting us", "Include your device model, operating-system version, app version, and the steps to reproduce the issue. You do not need to send your document content."),
 ],
 "delete_title": "Delete your PageBeam account and data",
 "delete_intro": "PageBeam works without signing in, and data is stored on our server only if you sign in and turn on cloud backup. You can delete it as follows.",
 "delete-account": [
  ("Delete in the app (recommended)", "In PageBeam, choose Settings → Account & backup → Delete account. All documents, signatures and subscription records on our server are deleted, and if you used Sign in with Apple the link is revoked. Subscriptions are not cancelled automatically, so cancel in the store separately."),
  ("If you cannot open the app", f"Email {EMAIL} with the sign-in method (Apple or Google) and the app name. After verifying it is you, we delete the data within 7 business days and let you know."),
  ("Data on your device", "Documents stored only on your device are removed when you delete the app. Deleting your account in the app does not delete documents on the device."),
  ("What is deleted", "PDF documents and previews uploaded to the cloud, signature images, document titles and folders, and subscription status records. Payment history in the stores is managed by Apple and Google and is not deleted."),
 ],
 "contact": "Contact", "skip": "Skip to content", "choose": "Choose language", "copyright": "© 2026 Next Studio",
}
