from pathlib import Path
from html import escape

ROOT = Path(__file__).parent
STORE_URL = "https://apps.apple.com/app/id6811864313"

LANGUAGES = {
    "ko": {"label": "한국어", "lang": "ko", "title": "Nono Pulse: Nonogram", "tag": "숫자로 완성하는 나만의 픽셀 그림", "intro": "행과 열의 숫자 힌트를 읽고 칸을 채워 숨은 그림을 찾아보세요.", "play": "두 가지 방식으로 즐기기", "playText": "컬러 픽처 모드와 전통적인 흑백 클래식 모드로 논리 퍼즐을 풀 수 있습니다.", "sizes": "작게 시작해 크게 도전하기", "sizesText": "5×5부터 30×30까지 원하는 크기를 고르고, 데일리 퍼즐과 이어하기로 나만의 속도로 즐기세요.", "compete": "기록에 도전하기", "competeText": "Apple 또는 Google 로그인으로 크기별 글로벌 랭킹에 참여할 수 있습니다.", "download": "App Store에서 다운로드", "privacy": "개인정보처리방침", "support": "도움말 및 지원", "hub": "언어 선택", "copyright": "© 2026 Next Studio"},
    "en": {"label": "English", "lang": "en", "title": "Nono Pulse: Nonogram", "tag": "Reveal a pixel picture, one square at a time.", "intro": "Read the number clues, fill the right cells, and uncover the picture hidden in the grid.", "play": "Two ways to play", "playText": "Choose colorful Picture Nonogram or a traditional monochrome Classic puzzle.", "sizes": "Start small, think big", "sizesText": "Choose grids from 5×5 to 30×30, try the daily puzzle, or save a regular puzzle for later.", "compete": "Challenge your best time", "competeText": "Sign in with Apple or Google to join global rankings for each puzzle size.", "download": "Download on the App Store", "privacy": "Privacy Policy", "support": "Help & Support", "hub": "Choose language", "copyright": "© 2026 Next Studio"},
    "ja": {"label": "日本語", "lang": "ja", "title": "Nono Pulse: Nonogram", "tag": "数字からピクセルアートを完成させよう", "intro": "行と列の数字を読み、マスを埋めて、隠れた絵を見つけましょう。", "play": "2つの遊び方", "playText": "カラフルなピクチャーノノグラムと、伝統的なモノクロのクラシックパズルを楽しめます。", "sizes": "小さく始めて大きく挑戦", "sizesText": "5×5から30×30まで選べます。デイリーパズルや途中保存したパズルも楽しめます。", "compete": "ベストタイムに挑戦", "competeText": "AppleまたはGoogleでログインすると、サイズ別の世界ランキングに参加できます。", "download": "App Storeでダウンロード", "privacy": "プライバシーポリシー", "support": "ヘルプとサポート", "hub": "言語を選択", "copyright": "© 2026 Next Studio"},
    "zh-hans": {"label": "简体中文", "lang": "zh-Hans", "title": "Nono Pulse: Nonogram", "tag": "用数字完成一幅像素画", "intro": "阅读行列数字提示，填满正确的格子，找出网格中隐藏的图案。", "play": "两种游玩方式", "playText": "可以选择彩色图案数织，或传统黑白经典数织。", "sizes": "从小格开始，挑战大格", "sizesText": "可选择 5×5 到 30×30 的棋盘，还可体验每日谜题或保存普通谜题稍后继续。", "compete": "挑战最佳时间", "competeText": "使用 Apple 或 Google 登录，即可参加各尺寸的全球排行榜。", "download": "在 App Store 下载", "privacy": "隐私政策", "support": "帮助与支持", "hub": "选择语言", "copyright": "© 2026 Next Studio"},
    "es": {"label": "Español", "lang": "es", "title": "Nono Pulse: Nonogram", "tag": "Revela un dibujo de píxeles, casilla a casilla.", "intro": "Lee las pistas numéricas, llena las casillas correctas y descubre la imagen escondida.", "play": "Dos formas de jugar", "playText": "Elige Nonogramas de imagen a color o un rompecabezas clásico monocromático.", "sizes": "Empieza pequeño, piensa en grande", "sizesText": "Elige cuadrículas de 5×5 a 30×30, prueba el puzle diario o guarda una partida para después.", "compete": "Desafía tu mejor tiempo", "competeText": "Inicia sesión con Apple o Google para participar en clasificaciones mundiales por tamaño.", "download": "Descargar en App Store", "privacy": "Política de privacidad", "support": "Ayuda y soporte", "hub": "Elegir idioma", "copyright": "© 2026 Next Studio"},
    "fr": {"label": "Français", "lang": "fr", "title": "Nono Pulse: Nonogram", "tag": "Révélez une image pixel par pixel.", "intro": "Lisez les indices chiffrés, remplissez les bonnes cases et découvrez l'image cachée.", "play": "Deux façons de jouer", "playText": "Choisissez un nonogramme illustré en couleur ou une grille classique monochrome.", "sizes": "Commencez petit, visez grand", "sizesText": "Choisissez des grilles de 5×5 à 30×30, essayez le puzzle du jour ou reprenez plus tard une partie enregistrée.", "compete": "Défiez votre meilleur temps", "competeText": "Connectez-vous avec Apple ou Google pour rejoindre les classements mondiaux par taille de grille.", "download": "Télécharger dans l’App Store", "privacy": "Politique de confidentialité", "support": "Aide et assistance", "hub": "Choisir la langue", "copyright": "© 2026 Next Studio"},
    "de": {"label": "Deutsch", "lang": "de", "title": "Nono Pulse: Nonogram", "tag": "Entdecke Pixelbilder, Feld für Feld.", "intro": "Lies die Zahlenhinweise, fülle die richtigen Felder und enthülle das versteckte Bild.", "play": "Zwei Spielarten", "playText": "Wähle farbige Bild-Nonogramme oder ein klassisches monochromes Rätsel.", "sizes": "Klein anfangen, groß denken", "sizesText": "Wähle Gitter von 5×5 bis 30×30, probiere das Tagesrätsel oder speichere ein Rätsel für später.", "compete": "Fordere deine Bestzeit heraus", "competeText": "Melde dich mit Apple oder Google an und nimm an globalen Ranglisten nach Rastergröße teil.", "download": "Im App Store laden", "privacy": "Datenschutzerklärung", "support": "Hilfe & Support", "hub": "Sprache wählen", "copyright": "© 2026 Next Studio"},
    "pt-br": {"label": "Português (Brasil)", "lang": "pt-BR", "title": "Nono Pulse: Nonogram", "tag": "Revele uma imagem em pixels, casa por casa.", "intro": "Leia as pistas numéricas, preencha as casas certas e descubra a imagem escondida.", "play": "Dois jeitos de jogar", "playText": "Escolha nonogramas coloridos de imagem ou um quebra-cabeça clássico monocromático.", "sizes": "Comece pequeno, pense grande", "sizesText": "Escolha grades de 5×5 a 30×30, experimente o puzzle diário ou salve um puzzle para continuar depois.", "compete": "Desafie seu melhor tempo", "competeText": "Entre com Apple ou Google para participar dos rankings globais por tamanho de grade.", "download": "Baixar na App Store", "privacy": "Política de Privacidade", "support": "Ajuda e suporte", "hub": "Escolher idioma", "copyright": "© 2026 Next Studio"},
}

STYLE = """<style>
:root{--ink:#30213d;--coral:#ff665c;--peach:#fff1ea;--violet:#6a4c93;--line:#eaded8}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 86% 0,#ffd9ca 0,transparent 30rem),linear-gradient(180deg,#fff6f1,#fff);font:16px/1.6 system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",sans-serif;color:var(--ink)}main{max-width:1040px;margin:auto;padding:24px 20px 64px}.top{display:flex;justify-content:space-between;align-items:center;gap:18px}.brand{font-weight:900;letter-spacing:.08em;color:var(--violet);text-decoration:none}.language{border:1px solid var(--line);border-radius:12px;padding:9px 30px 9px 11px;background:#fff;color:var(--ink);font:inherit}.hero{display:grid;grid-template-columns:1.25fr .75fr;gap:48px;align-items:center;padding:80px 5vw 68px}.eyebrow{font-size:.78rem;font-weight:800;letter-spacing:.16em;color:var(--coral)}h1{font-size:clamp(2.8rem,7vw,5.3rem);line-height:.98;letter-spacing:-.06em;margin:12px 0 22px}h2{font-size:1.28rem;margin:0 0 7px}.lead{font-size:1.15rem;max-width:34rem}.button{display:inline-block;margin-top:20px;padding:13px 20px;border-radius:999px;background:var(--ink);color:#fff;text-decoration:none;font-weight:800}.board{display:grid;grid-template-columns:repeat(5,1fr);gap:6px;padding:18px;background:#fff;border:1px solid var(--line);border-radius:28px;box-shadow:0 25px 55px #5d334020;transform:rotate(4deg)}.cell{aspect-ratio:1;border-radius:7px;background:#ffe7dd}.cell.on{background:var(--coral)}.cell.alt{background:var(--violet)}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.feature{background:#fff;border:1px solid var(--line);border-radius:20px;padding:24px}.feature p{margin:0}.links{display:flex;justify-content:center;flex-wrap:wrap;gap:18px;margin-top:56px}.links a{color:var(--violet);font-weight:700}.footer{text-align:center;color:#6b5b6f;font-size:.9rem;margin-top:24px}@media(max-width:720px){main{padding:18px 14px 42px}.hero{grid-template-columns:1fr;gap:34px;padding:52px 8px}.board{max-width:270px;justify-self:center}.features{grid-template-columns:1fr}h1{font-size:clamp(2.7rem,15vw,4rem)}}
</style>"""

def language_options(current):
    return "".join(f'<option value="../{code}/index.html" {"selected" if code == current else ""}>{escape(text["label"])}</option>' for code, text in LANGUAGES.items())

def page(code, data):
    cells = "".join(f'<span class="cell {klass}"></span>' for klass in ("on", "", "alt", "", "on", "", "alt", "on", "alt", "", "alt", "on", "on", "on", "alt", "", "alt", "on", "alt", "", "on", "", "alt", "", "on"))
    return f'''<!doctype html><html lang="{data['lang']}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="{escape(data['intro'])}"><title>{escape(data['title'])}</title>{STYLE}</head><body><main>
<header class="top"><a class="brand" href="../index.html">NONO PULSE</a><label><span style="position:absolute;left:-9999px">{escape(data['hub'])}</span><select class="language" aria-label="{escape(data['hub'])}" onchange="location.href=this.value">{language_options(code)}</select></label></header>
<section class="hero"><div><div class="eyebrow">NONOGRAM · LOGIC PUZZLE</div><h1>{escape(data['tag'])}</h1><p class="lead">{escape(data['intro'])}</p><a class="button" href="{STORE_URL}">{escape(data['download'])}</a></div><div class="board" aria-label="Nonogram pixel illustration">{cells}</div></section>
<section class="features"><article class="feature"><h2>{escape(data['play'])}</h2><p>{escape(data['playText'])}</p></article><article class="feature"><h2>{escape(data['sizes'])}</h2><p>{escape(data['sizesText'])}</p></article><article class="feature"><h2>{escape(data['compete'])}</h2><p>{escape(data['competeText'])}</p></article></section>
<nav class="links" aria-label="Links"><a href="../privacy.html">{escape(data['privacy'])}</a><a href="../support.html">{escape(data['support'])}</a></nav><footer class="footer">{escape(data['copyright'])}</footer></main></body></html>'''

def hub():
    links = "".join(f'<a href="{code}/index.html" hreflang="{data["lang"]}">{escape(data["label"])}</a>' for code, data in LANGUAGES.items())
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Nono Pulse: Nonogram official website"><title>Nono Pulse: Nonogram</title>{STYLE}</head><body><main><header class="top"><span class="brand">NONO PULSE</span></header><section class="hero"><div><div class="eyebrow">NONOGRAM · LOGIC PUZZLE</div><h1>Reveal a pixel picture, one square at a time.</h1><p class="lead">Choose a language to learn about Nono Pulse: Nonogram.</p></div><div class="board" aria-hidden="true">{''.join('<span class="cell on"></span>' if i in (0,2,6,7,8,10,11,12,13,14,17,22,24) else '<span class="cell"></span>' for i in range(25))}</div></section><nav class="features" aria-label="Languages">{links}</nav><footer class="footer">© 2026 Next Studio</footer></main></body></html>'''

for code, data in LANGUAGES.items():
    destination = ROOT / code
    destination.mkdir(exist_ok=True)
    (destination / "index.html").write_text(page(code, data), encoding="utf-8")
(ROOT / "index.html").write_text(hub(), encoding="utf-8")
